---
# This playbook runs a basic DF command.

- hosts: all

  tasks:
  - name: find disk space available.
    command: df -hPT
    register: diskspace
    
    
  - name: start an instance and Add EBS
  amazon.aws.ec2_instance:
    name: "public-with-ebs-instance"
    vpc_subnet_id: subnet-5ca1ab1e
    instance_type: t2.micro
    key_name: "a-ssh-key"
    security_group: default
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 16
          delete_on_termination: true
